export enum AuditLogAction {
  CREATE_CITY = 'CREATE_CITY',
  UPDATE_CITY = 'UPDATE_CITY',
  DELETE_CITY = 'DELETE_CITY',

  CREATE_FAQ = 'CREATE_FAQ',
  UPDATE_FAQ = 'UPDATE_FAQ',
  DELETE_FAQ = 'DELETE_FAQ',

  CREATE_ORDER = 'CREATE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  CREATE_ORDER_PAYMENT = 'CREATE_ORDER_PAYMENT',
  UPDATE_ORDER_PAYMENT = 'UPDATE_ORDER_PAYMENT',

  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  CREATE_PRODUCT_VARIANT = 'CREATE_PRODUCT_VARIANT',
  UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT',
  DELETE_PRODUCT_VARIANT = 'DELETE_PRODUCT_VARIANT',

  CREATE_REVIEW = 'CREATE_REVIEW',
  UPDATE_REVIEW = 'UPDATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',

  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER'
}
