export enum AuditLogAction {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  CREATE_PRODUCT_VARIANT = 'CREATE_PRODUCT_VARIANT',
  UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT',
  DELETE_PRODUCT_VARIANT = 'DELETE_PRODUCT_VARIANT',

  CREATE_ORDER = 'CREATE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER'
}
