export enum AdminPermission {
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',

  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  CREATE_CITY = 'CREATE_CITY',
  UPDATE_CITY = 'UPDATE_CITY',
  DELETE_CITY = 'DELETE_CITY',

  CREATE_FAQ = 'CREATE_FAQ',
  UPDATE_FAQ = 'UPDATE_FAQ',
  DELETE_FAQ = 'DELETE_FAQ',

  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  UPDATE_PAYMENT = 'UPDATE_PAYMENT',

  CREATE_PAYMENT_METHOD = 'CREATE_PAYMENT_METHOD',
  UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD',
  DELETE_PAYMENT_METHOD = 'DELETE_PAYMENT_METHOD',

  CREATE_PRODUCT_CATEGORY = 'CREATE_PRODUCT_CATEGORY',
  UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY',
  DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY',

  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  CREATE_PRODUCT_VARIANT = 'CREATE_PRODUCT_VARIANT',
  UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT',
  DELETE_PRODUCT_VARIANT = 'DELETE_PRODUCT_VARIANT',

  UPDATE_REVIEW = 'UPDATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',

  VIEW_CUSTOMER = 'VIEW_CUSTOMER',
  DELETE_CUSTOMER = 'DELETE_CUSTOMER',

  VIEW_ADMINISTRATOR = 'VIEW_ADMINISTRATOR',
  CREATE_ADMINISTRATOR = 'CREATE_ADMINISTRATOR',
  UPDATE_ADMINISTRATOR = 'UPDATE_ADMINISTRATOR',
  DELETE_ADMINISTRATOR = 'DELETE_ADMINISTRATOR',

  UPDATE_WEBSITE_TEXT = 'UPDATE_WEBSITE_TEXT'
}
