export enum AdminPermission {
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',

  VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOGS',

  VIEW_CITY = 'VIEW_CITY',
  CREATE_CITY = 'CREATE_CITY',
  UPDATE_CITY = 'UPDATE_CITY',
  DELETE_CITY = 'DELETE_CITY',

  VIEW_FAQ = 'VIEW_FAQ',
  CREATE_FAQ = 'CREATE_FAQ',
  UPDATE_FAQ = 'UPDATE_FAQ',
  DELETE_FAQ = 'DELETE_FAQ',

  VIEW_ORDER = 'VIEW_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  VIEW_PAYMENT_METHOD = 'VIEW_PAYMENT_METHOD',
  CREATE_PAYMENT_METHOD = 'CREATE_PAYMENT_METHOD',
  UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD',
  DELETE_PAYMENT_METHOD = 'DELETE_PAYMENT_METHOD',

  VIEW_PRODUCT_CATEGORY = 'VIEW_PRODUCT_CATEGORY',
  CREATE_PRODUCT_CATEGORY = 'CREATE_PRODUCT_CATEGORY',
  UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY',
  DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY',

  VIEW_PRODUCT = 'VIEW_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  VIEW_PRODUCT_VARIANT = 'VIEW_PRODUCT_VARIANT',
  CREATE_PRODUCT_VARIANT = 'CREATE_PRODUCT_VARIANT',
  UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT',
  DELETE_PRODUCT_VARIANT = 'DELETE_PRODUCT_VARIANT',

  VIEW_REVIEW = 'VIEW_REVIEW',
  UPDATE_REVIEW = 'UPDATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',

  VIEW_USER = 'VIEW_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  VIEW_WEBSITE_TEXT = 'VIEW_WEBSITE_TEXT',
  UPDATE_WEBSITE_TEXT = 'UPDATE_WEBSITE_TEXT'
}
